# Generated by Django 5.0.7 on 2024-07-14 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='dateNew',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
