# Generated by Django 5.0.7 on 2024-07-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_datenew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
    ]
