# Generated by Django 5.0.7 on 2024-07-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_remove_tournament_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='dateNew',
            new_name='date',
        ),
    ]
