# Generated by Django 5.0.7 on 2024-07-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_rename_datenew_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='matchType',
            field=models.CharField(choices=[('One Way', 'One Way'), ('Each Way', 'Each Way')], default='One Way', max_length=10),
        ),
    ]
