# Generated by Django 5.0.7 on 2024-07-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_matchtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='liveScores',
            field=models.BooleanField(default=False),
        ),
    ]
