# Generated by Django 5.0.7 on 2024-07-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_remove_entry_user_entry_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='profile',
            new_name='user',
        ),
    ]
