# Generated by Django 5.0.7 on 2024-07-16 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_rename_profile_entry_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='teamName',
            field=models.CharField(default='Team Name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='userNew',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
