# Generated by Django 5.0.7 on 2024-07-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_entry_usernew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user',
        ),
    ]
