# Generated by Django 5.0.7 on 2024-07-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_remove_entry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='userNew',
            new_name='user',
        ),
    ]
