# Generated by Django 5.0.7 on 2024-07-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='umpireOne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='umpireTwo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
