# Generated by Django 5.0.7 on 2024-07-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_entry_umpire'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='umpires',
            field=models.BooleanField(default=False),
        ),
    ]
