# Generated by Django 5.0.7 on 2024-07-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_tournament_umpires'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='entryPrice',
            field=models.IntegerField(default=0),
        ),
    ]
