# Generated by Django 5.0.7 on 2024-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_tournament_entryprice_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='entryPrice_currency',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='entryPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
