# Generated by Django 5.0.7 on 2024-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_remove_tournament_entryprice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='vat',
            field=models.BooleanField(default=True),
        ),
    ]
