# Generated by Django 5.0.7 on 2024-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0026_entry_teamsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='teamsheet',
            field=models.FileField(blank=True, null=True, upload_to='team-sheets/'),
        ),
    ]
