# Generated by Django 5.0.7 on 2024-07-24 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(choices=[('U8', 'Under 8s'), ('U9', 'Under 9s'), ('U10', 'Under 10s'), ('U11', 'Under 11s'), ('U12', 'Under 12s'), ('U13', 'Under 13s'), ('U14', 'Under 14s'), ('U15', 'Under 15s'), ('U16', 'Under 16s'), ('U17', 'Under 17s'), ('U18', 'Under 18s'), ('Mixed', 'Mixed ages')], max_length=5)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Mixed', 'Mixed')], max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('noTeams', models.IntegerField(default=0)),
                ('matchType', models.CharField(choices=[('One Way', 'One Way'), ('Each Way', 'Each Way')], default='One Way', max_length=10)),
                ('matchDuration', models.IntegerField(default=15)),
                ('halftimeDuration', models.IntegerField(default=0)),
                ('breakDuration', models.IntegerField(default=5)),
                ('generatedSchedule', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('County', 'County'), ('Regional', 'Regional'), ('National', 'National'), ('N/A', 'N/A')], max_length=10)),
                ('group', models.CharField(choices=[('School', 'School'), ('Club', 'Club'), ('Social', 'Social'), ('County', 'County'), ('N/A', 'N/A')], max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('forGoals', models.IntegerField(default=0)),
                ('againstGoals', models.IntegerField(default=0)),
                ('goalDiff', models.IntegerField(default=0)),
                ('played', models.IntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.BooleanField(default=False)),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('pitch', models.IntegerField(default=1)),
                ('start', models.TimeField(blank=True)),
                ('goalsOne', models.IntegerField(default=0)),
                ('goalsTwo', models.IntegerField(default=0)),
                ('entryOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='One', to='leagues.leagueentry')),
                ('entryTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Two', to='leagues.leagueentry')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
    ]
