# Generated by Django 5.0.7 on 2024-07-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='breakDuration',
        ),
    ]
