# Generated by Django 5.0.7 on 2024-07-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_rename_tournament_leaguematch_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguematch',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguematch',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguematch',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
