# Generated by Django 5.0.7 on 2024-07-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_alter_leaguematch_date_alter_leaguematch_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguematch',
            name='data',
            field=models.BooleanField(default=False),
        ),
    ]
