# Generated by Django 5.0.7 on 2024-07-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_leaguematch_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
