# Generated by Django 5.0.7 on 2024-08-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_discount_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='paid',
        ),
    ]
