# Generated by Django 5.0.7 on 2024-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timed',
            field=models.CharField(choices=[('Centrally Timed', 'Centrally Timed'), ('Umpire Timed', 'Umpire Timed')], default='Centrally Timed', max_length=15),
        ),
    ]
