# Generated by Django 5.0.7 on 2024-07-21 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_rules_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='timings',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timings',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
