# Generated by Django 5.0.7 on 2024-07-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_timings_end_timings_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timings',
            name='end',
        ),
        migrations.RemoveField(
            model_name='timings',
            name='start',
        ),
    ]
