# Generated by Django 5.0.7 on 2024-07-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_rules_order_timings_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.BooleanField(default=False),
        ),
    ]
