# Generated by Django 5.0.7 on 2024-07-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_schedule_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule',
            new_name='pdf',
        ),
    ]
