# Generated by Django 5.0.7 on 2024-07-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_rename_schedule_schedule_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
