# Generated by Django 5.0.7 on 2024-07-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_schedule_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='pdf',
            new_name='publishPdf',
        ),
    ]
